#!/bin/bash

HEIGHT=25
WIDTH=160
CHOICE_HEIGHT=24
BACKTITLE="AltaeraAI - v6.0.3 | RAM:$(free -m | awk '/^Mem:/{printf("%.1fG\n",$2/1000)}') | Free Storage:$(df -Ph . | tail -1 | awk '{print $4}')"
TITLE="AI Model Selection"
MENU="Choose your desired rwkv-6-world-7b-GGUF model size/strategy:"

OPTIONS=(1 "[...] Go Back"
         2 "q2_k-rwkv-6-world-7b.gguf \ 2.96 GB"
         3 "q3_k-rwkv-6-world-7b.gguf \ 3.7 GB"
         4 "q3_k_l-rwkv-6-world-7b.gguf \ 3.7 GB"
         5 "q4_0-rwkv-6-world-7b.gguf \ 4.66 GB"
         6 "q4_0_4_4-rwkv-6-world-7b.gguf \ 4.66 GB"
         7 "q4_0_4_8-rwkv-6-world-7b.gguf \ 4.66 GB"
         8 "q4_0_8_8-rwkv-6-world-7b.gguf \ 4.66 GB"
         9 "q4_1-rwkv-6-world-7b.gguf \ 5.12 GB"
         10 "q4_k-rwkv-6-world-7b.gguf \ 4.66 GB"
         11 "q4_k_s-rwkv-6-world-7b.gguf \ 4.66 GB"
         12 "q5_0-rwkv-6-world-7b.gguf \ 5.57 GB"
         13 "q5_1-rwkv-6-world-7b.gguf \ 6.03 GB"
         14 "q5_k-rwkv-6-world-7b.gguf \ 5.57 GB"
         15 "q5_k_s-rwkv-6-world-7b.gguf \ 5.57 GB"
         16 "q6_k-rwkv-6-world-7b.gguf \ 6.54 GB"
         17 "q8_0-rwkv-6-world-7b.gguf \ 8.37 GB"
         18 "bf16-rwkv-6-world-7b.gguf \ 15.4 GB"
         19 "f16-rwkv-6-world-7b.gguf \ 15.5 GB"
         20 "f32-rwkv-6-world-7b.gguf \ 30.5 GB")


CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

        1)
            ./AltaeraAI/altaera-model.sh
            ;;
        2)
            echo "You chose 'q2_k-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q2_k.gguf -O 'q2_k-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        3)
            echo "You chose 'q3_k-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q3_k.gguf -O 'q3_k-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        4)
            echo "You chose 'q3_k_l-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q3_k_l.gguf -O 'q3_k_l-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        5)
            echo "You chose 'q4_0-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_0.gguf -O 'q4_0-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        6)
            echo "You chose 'q4_0_4_4-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_0_4_4.gguf -O 'q4_0_4_4-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        7)
            echo "You chose 'q4_0_4_8-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_0_4_8.gguf -O 'q4_0_4_8-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        8)
            echo "You chose 'q4_0_8_8-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_0_8_8.gguf -O 'q4_0_8_8-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        9)
            echo "You chose 'q4_1-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_1.gguf -O 'q4_1-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        10)
            echo "You chose 'q4_k-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_k.gguf -O 'q4_k-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;

        11)
            echo "You chose 'q4_k_s-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q4_k_s.gguf -O 'q4_k_s-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;

        12)
            echo "You chose 'q5_0-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q5_0.gguf -O 'q5_0-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;

        13)
            echo "You chose 'q5_1-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q5_1.gguf -O 'q5_1-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        14)
            echo "You chose 'q5_k-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q5_k.gguf -O 'q5_k-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        15)
            echo "You chose 'q5_k_s-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q5_k_s.gguf -O 'q5_k_s-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        16)
            echo "You chose 'q6_k-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q6_k.gguf -O 'q6_k-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        17)
            echo "You chose 'q8_0-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-q8_0.gguf -O 'q8_0-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        18)
            echo "You chose 'bf16-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-bf16.gguf -O 'bf16-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
        19)
            echo "You chose 'f16-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-f16.gguf -O 'f16-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;

        20)
            echo "You chose 'f32-rwkv-6-world-7b.gguf'
                        
            To abort download, press 'Ctrl+C'
            [don't forget to delete the file afterwards]
            
            "
            {
            mkdir '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            } &> /dev/null 2>&1;
            cd '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera/root/models'
            rm -rf 'RWKV-model.bin'
            rm -rf 'model.bin'
            wget https://huggingface.co/latestissue/rwkv-6-world-7b-gguf/resolve/main/rwkv-6-world-7b-f32.gguf -O 'f32-rwkv-6-world-7b.gguf' -q --show-progress
            cd /root
            clear
            ;;
esac
